# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download base branch's coverage file
        uses: actions/download-artifact@v3
        with:
          name: "coverage_${{ env.GITHUB_RUN_ID }}"

      - name: Upload base branch's coverage file to develop branch's folder
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.GITHUB_REF }}"
          path: ./coverage-final.json
          
          
