# This is a basic workflow to help you get started with Actions

name: CI when PR

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2

      - name: Install Package
        run: npm install
      
      - name: Generate Coverage File
        run: npm run test:cov
        
      - name: Download develop branch's coverage file
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.GITHUB_REF }}
          path: ./coverage/base
      
      - name: "Check file existence"
        id: check_file
        uses: andstor/file-existence-action@v1
        with:
          files: "./coverage/base/coverage-final.json"
      
      - if: ${{ steps.check_file.outputs.files_exists == 'true' }}
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/base/report.json

      - uses: actions/upload-artifact@v3
        with:
          name: coverage_${{ github.run_id }}
          path: ./coverage/coverage-final.json
