# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test_coverage_when_pr.yml
          path: ./

      - name: Upload base branch's coverage file to develop branch's folder
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GITHUB_REF }}
          path: ./coverage-final.json
          
          
